name: 发布到华为云

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  judge:
    if: contains(github.event.head_commit.message, 'docs:')
    runs-on: ubuntu-latest
    steps:
        - name: Extract version from commit message
          run: |
            COMMIT_MSG=$(echo '${{ github.event.head_commit.message }}' | grep -oP '(?<=docs:)\d+\.\d+')
            if [ -z "$COMMIT_MSG" ]; then
              echo "没有指定需要发布的版本"
              exit 1  
            fi
            echo "将构建版本： $COMMIT_MSG !"

  deploy:
    needs: judge
    runs-on: ubuntu-latest
    steps:
      - name: 提取版本信息
        id: extract
        run: |
            COMMIT_MSG=$(echo '${{ github.event.head_commit.message }}' | grep -oP '(?<=docs:)\d+\.\d+')
            echo "::set-output name=version::$COMMIT_MSG"
      
      - uses: actions/checkout@v4

      - name: 设置 node 环境
        uses: actions/setup-node@v4
        with:
            node-version: 22
            cache: 'npm'

      - name: 安装依赖
        run: npm install

      - name: 构建项目
        run: npx vitepress build versions/${{ steps.extract.outputs.version }}

      - name: 登录华为云
        uses: huaweicloud/auth-action@v1.0.0
        with: 
            access_key_id: ${{ secrets.ACCESSKEY }} 
            secret_access_key: ${{ secrets.SECRETACCESSKEY }}
            region: 'cn-north-4'  
        
            
      # 由于最新版的发布路径是不带版本号的，所以需要特殊处理，当前最新版是 3.8  
      # 后期最新版为 3.9 的时候，需要将这边的判断条件从 3.8 改为 3.9

      - name: 上传文件到华为云(测试环境-最新版)
        uses: huaweicloud/obs-helper@master
        if: ${{ steps.extract.outputs.version == '3.8' }}
        with:
          bucket_name: 'cce-creator-docs-test'
          local_file_path: ./versions/${{ steps.extract.outputs.version }}/.vitepress/dist
          obs_file_path: gitbook/creator/manual/
          operation_type: upload 
          include_self_folder: false 
          
      - name: 上传文件到华为云(正式环境-最新版)
        uses: huaweicloud/obs-helper@master
        if: ${{ steps.extract.outputs.version == '3.8' && contains(github.event.head_commit.message, 'publish:docs:') }}  
        with:
          bucket_name: 'cce-creator-docs-pro'
          local_file_path: ./versions/${{ steps.extract.outputs.version }}/.vitepress/dist
          obs_file_path: gitbook/creator/manual/
          operation_type: upload 
          include_self_folder: false     

      
      # 按版本上传到对应的文件去

      - name: 上传文件到华为云(测试环境)
        uses: huaweicloud/obs-helper@master
        with:
          bucket_name: 'cce-creator-docs-test'
          local_file_path: ./versions/${{ steps.extract.outputs.version }}/.vitepress/dist
          obs_file_path: gitbook/creator/${{ steps.extract.outputs.version }}/manual/
          operation_type: upload 
          include_self_folder: false
          
      - name: 上传文件到华为云（正式环境）
        if: contains(github.event.head_commit.message, 'publish:docs:')  
        uses: huaweicloud/obs-helper@master
        with:
            bucket_name: 'cce-creator-docs-pro'
            local_file_path: ./versions/${{ steps.extract.outputs.version }}/.vitepress/dist
            obs_file_path: gitbook/creator/${{ steps.extract.outputs.version }}/manual/
            operation_type: upload 
            include_self_folder: false    
    